from . import hr_employee
from . import ir_attachment
from . import hr_leave_odoobot_notify_rule
from . import hr_leave_odoobot_notify
from . import hr_leave_discuss_notify
from . import hr_leave_type
from . import hr_leave_type_special_employee_line
from . import hr_leave_type_special_director_order_line
from . import hr_leave_store_chain
from . import hr_leave_p1_p2_split
from . import hr_leave_multi_step
from . import hr_leave_responsible_approval
from . import hr_leave_refuse_wizard
from . import hr_leave
from . import hr_leave_allocation
from . import hr_holidays_cancel_leave
