{
    "name": "Time Off Work Handover",
    "version": "19.0.1.0.25",
    "category": "Human Resources",
    "summary": "Work handover workflow for time off requests",
    "depends": [
        "hr_holidays",
        "business_discuss_bots",
        "time_off_extra_approval",
        "time_off_responsible_approval",
    ],
    "post_init_hook": "post_init_hook",
    "data": [
        "data/mail_activity_type_data.xml",
        "data/ir_cron_data.xml",
        "security/handover_security.xml",
        "security/hr_leave_type_rule_relaxed.xml",
        "security/ir.model.access.csv",
        "security/hr_leave_handover_replacement_draft_access.xml",
        "views/hr_leave_form_handover_views.xml",
        "views/hr_leave_form_emergency_views.xml",
        "views/hr_leave_multi_step_views.xml",
        "views/hr_leave_refuse_wizard_views.xml",
        "views/hr_leave_search_views.xml",
        "views/hr_leave_kanban_extra_approval.xml",
        "views/hr_leave_list_extra_approval.xml",
        "views/hr_leave_handover_refuse_wizard_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "time_off_work_handover/static/src/scss/handover_replacement.scss",
            "time_off_work_handover/static/src/scss/hr_leave_list_handover.scss",
        ],
    },
    "installable": True,
    "application": False,
    "license": "LGPL-3",
}
