# -*- coding: utf-8 -*-
{
    "name": "Quản lý dịch vụ",
    "version": "19.0.2.446.0",
    "category": "Operations",
    "summary": "Quản lý dịch vụ: Internet, Camera, Máy chấm công, LinkQ ERP, Máy chủ",
    "description": """
Quản lý dịch vụ
===============
* 1 app trên App Center: Quản lý dịch vụ
* Bên trong gồm 5 phân hệ: Internet, Camera, Máy chấm công, LinkQ ERP, Máy chủ
* Hub chọn dịch vụ + dashboard / hợp đồng / thanh toán theo từng phân hệ
* Phân quyền theo nhóm (giống Nhóm quyền LUG): Users + Xem/Thêm/Sửa/Xóa…
    """,
    "author": "Custom",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "mail",
        "hr",
        "hr_store",
        "lug_permission",
    ],
    "data": [
        "security/phan_he_security.xml",
        "security/security.xml",
        "security/linkq_erp_security.xml",
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "security/security_rules.xml",
        "data/ir_sequence_data.xml",
        "data/phan_he_service_type_data.xml",
        "data/phan_he_work_shift_data.xml",
        "data/shift_schedule_north_data.xml",
        "data/shift_schedule_dtt_data.xml",
        "data/shift_initial_data.xml",
        "data/lug_app_data.xml",
        "data/phan_he_demo.xml",
        "data/phan_he_lang_date.xml",
        "data/roster_lock_cron.xml",
        "data/shift_guide_document_data.xml",
        "views/phan_he_views.xml",
        "views/phan_he_work_shift_views.xml",
        "views/shift_schedule_north_views.xml",
        "views/shift_schedule_dtt_views.xml",
        "views/shift_management_views.xml",
        "views/phan_he_shift_roster_views.xml",
        "views/monthly_matrix_views.xml",
        "views/hr_store_asm_email_views.xml",
        "data/email_template_monthly_roster.xml",
        "views/phan_he_payment_file_views.xml",
        "views/phan_he_app_actions.xml",
        "views/phan_he_hub_action.xml",
        "views/phan_he_access_views.xml",
        "views/lug_menu_permission_views.xml",
        "views/linkq_store_permission_views.xml",
        "views/menu_access_views.xml",
        "views/phan_he_access_action.xml",
        "data/phan_he_access_group_data.xml",
        "data/linkq_access_presets.xml",
        "views/linkq_employee_views.xml",
        "views/linkq_today_shift_views.xml",
        "views/phan_he_menus.xml",
        "data/phan_he_clear_submenu_icons.xml",
        "views/res_users_views.xml",
        "views/hr_employee_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "lug_phan_he/static/src/js/sidebar_controller.js",
            "lug_phan_he/static/src/js/sidebar_controller.js",
            "lug_phan_he/static/src/scss/sidebar_toolbar.scss",
            "lug_phan_he/static/src/scss/style.scss",
            "lug_phan_he/static/src/shell/phan_he_app_sidebar.scss",
            "lug_phan_he/static/src/scss/guide_docs_popup.scss",
            "lug_phan_he/static/src/scss/linkq_menu_perm.scss",
            "lug_phan_he/static/src/js/guide_docs_dialog.js",
            "lug_phan_he/static/src/xml/guide_docs_dialog.xml",
            "lug_phan_he/static/src/scss/store_notification.scss",
            "lug_phan_he/static/src/shift/store_notif_popup.js",
            "lug_phan_he/static/src/views/store_notification_popup.xml",
            "lug_phan_he/static/src/shell/phan_he_app_sidebar.js",
            "lug_phan_he/static/src/shell/phan_he_app_sidebar.xml",
            "lug_phan_he/static/src/hub/phan_he_hub.scss",
            "lug_phan_he/static/src/shift/phan_he_work_shift.scss",
            "lug_phan_he/static/src/scss/monthly_matrix_table.scss",
            "lug_phan_he/static/src/scss/monthly_roster_dashboard.scss",
            "lug_phan_he/static/src/scss/roster_lock_dashboard.scss",
            "lug_phan_he/static/src/shift/roster_lock_dashboard.js",
            "lug_phan_he/static/src/shift/roster_lock_panel.xml",
            "lug_phan_he/static/src/scss/roster_lock_settings.scss",
            "lug_phan_he/static/src/shift/roster_lock_settings.js",
            "lug_phan_he/static/src/shift/roster_lock_settings.xml",
            "lug_phan_he/static/src/shift/roster_list_board.js",
            "lug_phan_he/static/src/shift/roster_list_board.xml",
            "lug_phan_he/static/src/scss/summary_report.scss",
            "lug_phan_he/static/src/report/summary_report.js",
            "lug_phan_he/static/src/report/summary_report.xml",
            "lug_phan_he/static/src/shift/monthly_matrix_grid.js",
            "lug_phan_he/static/src/shift/monthly_matrix_grid.xml",
            "lug_phan_he/static/src/scss/custom_sidebar.scss",
            "lug_phan_he/static/src/scss/sidebar_tree.scss",
            "lug_phan_he/static/src/scss/linkq_subpanel.scss",
            "lug_phan_he/static/src/shift/phan_he_work_shift_list.js",
            "lug_phan_he/static/src/shift/phan_he_work_shift_list.xml",
            "lug_phan_he/static/src/hub/phan_he_hub.js",
            "lug_phan_he/static/src/hub/phan_he_hub.xml",
            "lug_phan_he/static/src/scss/menu_tree.scss",
            "lug_phan_he/static/src/xml/menu_tree_template.xml",
            "lug_phan_he/static/src/js/menu_tree_widget.js",
            "lug_phan_he/static/src/access/phan_he_access_matrix.js",
            "lug_phan_he/static/src/access/linkq_permission_matrix.scss",
            "lug_phan_he/static/src/access/linkq_permission_matrix.js",
            "lug_phan_he/static/src/access/linkq_permission_matrix.xml",
            "lug_phan_he/static/src/internet_shell/phan_he_internet_shell.scss",
            "lug_phan_he/static/src/internet_shell/phan_he_internet_shell.js",
            "lug_phan_he/static/src/internet_shell/phan_he_internet_shell.xml",
            "lug_phan_he/static/src/internet_list/phan_he_internet_list.scss",
            "lug_phan_he/static/src/internet_list/phan_he_internet_list.js",
            "lug_phan_he/static/src/internet_list/phan_he_internet_list.xml",
            "lug_phan_he/static/src/payment_board/phan_he_payment_board.scss",
            "lug_phan_he/static/src/payment_board/phan_he_payment_board.js",
            "lug_phan_he/static/src/payment_board/phan_he_payment_board.xml",
            "lug_phan_he/static/src/internet_entry/phan_he_internet_entry_popup.scss",
            "lug_phan_he/static/src/internet_entry/phan_he_internet_entry_popup.js",
            "lug_phan_he/static/src/internet_entry/phan_he_internet_entry_popup.xml",
            "lug_phan_he/static/src/dashboard/phan_he_dashboard.scss",
            "lug_phan_he/static/src/dashboard/internet_overview.scss",
            "lug_phan_he/static/src/internet_form/phan_he_internet_form.scss",
            "lug_phan_he/static/src/internet_form/phan_he_internet_form.js",
            "lug_phan_he/static/src/internet_form/phan_he_internet_form.xml",
            "lug_phan_he/static/src/access/internet_menu_nav.js",
            "lug_phan_he/static/src/access/phan_he_session_logout.js",
            "lug_phan_he/static/src/dashboard/phan_he_dashboard.js",
            "lug_phan_he/static/src/dashboard/phan_he_dashboard.xml",
            "lug_phan_he/static/src/dashboard/store_dashboard.scss",
            "lug_phan_he/static/src/dashboard/store_dashboard.js",
            "lug_phan_he/static/src/dashboard/store_dashboard.xml",
            "lug_phan_he/static/src/fields/ops_status_field.js",
            "lug_phan_he/static/src/fields/ops_status_field.xml",
            "lug_phan_he/static/src/fields/bandwidth_field.js",
            "lug_phan_he/static/src/fields/bandwidth_field.xml",
            "lug_phan_he/static/src/fields/phan_he_store_card_field.js",
            "lug_phan_he/static/src/fields/phan_he_store_card_field.xml",
            "lug_phan_he/static/src/tracking/phan_he_tracking.scss",
            "lug_phan_he/static/src/tracking/phan_he_tracking_list.js",
            "lug_phan_he/static/src/tracking/phan_he_tracking_list.xml",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}
