{
    "name": "Time Off Extra Approvers (Demo)",
    "version": "19.0.7.2.32",
    "category": "Human Resources",
    "summary": "Allow extra officers/offices to approve time off by leave type",
    "depends": [
        "hr_holidays",
        "hr_employee_multi_responsible",
        "hr_job_title_vn",
        "hr_employee_hrm_detail",
        "business_discuss_bots",
    ],
    "post_init_hook": "post_init_hook",
    "data": [
        "security/extra_approvers_security.xml",
        "security/hr_leave_type_write_access.xml",
        "security/ir.model.access.csv",
        "views/hr_leave_type_views.xml",
        "views/hr_leave_form_mobile_date_views.xml",
        "views/hr_leave_form_refusal_views.xml",
        "views/hr_leave_odoobot_notify_config_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "time_off_extra_approval/static/src/scss/timeoff_discuss_bot_link.scss",
            "time_off_extra_approval/static/src/scss/odoobot_notify_config.scss",
            "time_off_extra_approval/static/src/js/many2one_save_on_change_field.js",
            "time_off_extra_approval/static/src/js/timeoff_cancel_dialog_fix.js",
            "time_off_extra_approval/static/src/js/emergency_leave_form_controller.js",
            "time_off_extra_approval/static/src/js/discuss_time_off_link_patch.js",
            "time_off_extra_approval/static/src/js/error_dialog_vi_patch.js",
            "time_off_extra_approval/static/src/xml/error_dialog_vi_patch.xml",
            "time_off_extra_approval/static/src/xml/timeoff_form_dialog_buttons_patch.xml",
            "time_off_extra_approval/static/src/xml/time_off_dashboard_hrm_patch.xml",
            "time_off_extra_approval/static/src/js/time_off_dashboard_hrm_patch.js",
            "time_off_extra_approval/static/src/scss/time_off_dashboard_mobile.scss",
            "time_off_extra_approval/static/src/scss/time_off_leave_form_mobile.scss",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3"
}
